### ISSUE TITLE
error !!

### ISSUE THREAD

**Issue by rashedomar** [esdalmaijer/webcam-eyetracker#10]
Traceback (most recent call last):
  File "webcam.py", line 242, in <module>
    minsize=(30, 30))
  File "C:\Users\rashed\Desktop\eyemouse\webcam-eyetracker\PyOpenCV\pygazetracker\generic.py", line 758, in _crop_face
    flags = cv2.cv.CV_HAAR_SCALE_IMAGE
AttributeError: 'module' object has no attribute 'cv'

**Comment by DaddyWesker** [comment]
replace with cv2.CASCADE_SCALE_IMAGE
